# 
# HTTP requests catalog (use in Code, IntelliJ, ...)
#
# Requires the following env variables to be accessible:
#
#     - api-endpoint : absolute path to the endpoint 
#     - api-key      : api key to use for invoking the endpoint
#

# Trigger the job
GET {{api-endpoint}}
Authorization: {{api-key}}