#
# Default configuration file.
#
#
spring.profiles.active: production

mediafiles:
  #
  # What is the expected date pattern in the photo- and video filenames?
  # ( EXIF data is not used as datetime source )
  #
  datepattern: yyyy-MM-dd HH.mm.ss
  #
  # What kind of media files would you like to be organized?
  #
  mediaFileExtensionsToMatch: jpg,mov

destination:
  #
  # How many photos/videos should appear within a day before we consider them an actual event?
  # (inclusive value)
  #
  amountOfMediaFilesIndicatingAnEvent: 10
  #
  # When generating the "month" name in destination folders, which locale do you want to use?
  #
  localeForGeneratingDestinationFolderNames: en_UK
  #
  # What should the suffix be of the monthly folder that contains occational photos/videos?
  #
  suffixForDestinationFolderOfMiscMediaFiles: Misc
  #
  # What should the suffix be of the folders containing events?
  #
  suffixForDestinationFolderOfUnknownEventMediaFiles: This Must Be An Event