name: Hello World Workflow

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  hello-world-job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Say Hello World
        run: echo "Hello, World!"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOYMENT_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
          role-session-name: GitHubActionsMediaOrganizerDeployment
          mask-aws-account-id: true

      - name: AWS S3 count buckets
        run: |
          aws s3 ls | wc -l
