name: Hello World Workflow

on:
  push:
    branches:
      - master

jobs:
  hello-world-job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Say Hello World
        run: echo "Hello, World!"
